spring.application.name=HVH-BE

spring.datasource.url=${DB_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/hvh-db
#spring.datasource.username=postgres
#spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# enable flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

#hibernate just check schema (map)
spring.jpa.hibernate.ddl-auto=validate
