spring.application.name=HVH-BE

spring.datasource.url=${DB_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/hvh-db
#spring.datasource.username=postgres
#spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# enable flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

#hibernate just check schema (map)
spring.jpa.hibernate.ddl-auto=validate

#upload file size limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

#supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SP_JWT_ISSUER_URI}

supabase.url=${SP_URL}
supabase.api-secret-key=${SP_API_SECRET_KEY}
supabase.bucket=${SP_BUCKET_NAME}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true