spring.application.name=HVH-BE

spring.datasource.url=${DB_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/hvh-db
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# enable flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

#hibernate just check schema (map)
spring.jpa.hibernate.ddl-auto=validate

#upload file size limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

#supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SP_JWT_ISSUER_URI}

supabase.url=${SP_URL}
supabase.api-secret-key=${SP_API_SECRET_KEY}
supabase.bucket=${SP_BUCKET_NAME}

#springdoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${EMAIL_USERNAME}
#spring.mail.password=${EMAIL_PASSWORD}
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#rabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=${RBMQ_USERNAME}
#spring.rabbitmq.password=${RBMQ_PASSWORD}
#spring.rabbitmq.virtual-host=/
#spring.rabbitmq.listener.simple.acknowledge-mode=auto
#spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.rabbitmq.addresses=${RBMQ_AMQP_URL}

rabbitmq.mail.exchange=mail_exchange

rabbitmq.mail.queue.send=mail_send
rabbitmq.mail.queue.retry1=mail_retry1
rabbitmq.mail.queue.retry2=mail_retry2
rabbitmq.mail.queue.retry3=mail_retry3
rabbitmq.mail.queue.dlq=mail_dlq

rabbitmq.mail.routing.send=mail_send
rabbitmq.mail.routing.retry1=mail_retry1
rabbitmq.mail.routing.retry2=mail_retry2
rabbitmq.mail.routing.retry3=mail_retry3
rabbitmq.mail.routing.dlq=mail_dlq
#30s
rabbitmq.mail.retry.ttl1=30000
#3m
rabbitmq.mail.retry.ttl2=180000
#5m
rabbitmq.mail.retry.ttl3=300000

#redis
spring.data.redis.host=${RD_HOST}
spring.data.redis.port=${RD_PORT}
spring.data.redis.password=${RD_PASSWORD}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.initialization-fail-timeout=0