CREATE TABLE roles
(
    id         SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                               NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);